-- MySQL Script generated by MySQL Workbench
-- Thu Jun 30 10:20:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sentinel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sentinel` ;

-- -----------------------------------------------------
-- Schema sentinel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sentinel` DEFAULT CHARACTER SET utf8 ;
USE `sentinel` ;

-- -----------------------------------------------------
-- Table `sentinel`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentinel`.`address` ;

CREATE TABLE IF NOT EXISTS `sentinel`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL,
  `number` VARCHAR(45) NULL,
  `addition` VARCHAR(255) NULL,
  `postcode` VARCHAR(45) NULL,
  `city` VARCHAR(255) NULL,
  `province` VARCHAR(255) NULL,
  `latitude` DECIMAL(11,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sentinel`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentinel`.`report` ;

CREATE TABLE IF NOT EXISTS `sentinel`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(255) NOT NULL,
  `report_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `employer_name` VARCHAR(255) NULL,
  `employment_agency_name` VARCHAR(255) NULL,
  `branch_type` VARCHAR(255) NULL,
  `max_households` INT NULL,
  `num_people` INT NULL,
  `remark` VARCHAR(1000) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_case_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_case_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `sentinel`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sentinel`.`situation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentinel`.`situation` ;

CREATE TABLE IF NOT EXISTS `sentinel`.`situation` (
  `id` VARCHAR(25) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sentinel`.`report_has_situation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentinel`.`report_has_situation` ;

CREATE TABLE IF NOT EXISTS `sentinel`.`report_has_situation` (
  `report_id` INT NOT NULL,
  `situation_id` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`report_id`, `situation_id`),
  INDEX `fk_report_has_situation_situation1_idx` (`situation_id` ASC) VISIBLE,
  INDEX `fk_repoert_has_situation_case_idx` (`report_id` ASC) VISIBLE,
  CONSTRAINT `fk_case_has_situation_case`
    FOREIGN KEY (`report_id`)
    REFERENCES `sentinel`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_has_situation_situation1`
    FOREIGN KEY (`situation_id`)
    REFERENCES `sentinel`.`situation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sentinel`.`offense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentinel`.`offense` ;

CREATE TABLE IF NOT EXISTS `sentinel`.`offense` (
  `id` INT NOT NULL,
  `law` VARCHAR(45) NOT NULL,
  `article` VARCHAR(45) NOT NULL,
  `sub` VARCHAR(45) NULL,
  `criminal_law` TINYINT NOT NULL,
  `website` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sentinel`.`situation_has_offense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentinel`.`situation_has_offense` ;

CREATE TABLE IF NOT EXISTS `sentinel`.`situation_has_offense` (
  `situation_id` VARCHAR(25) NOT NULL,
  `offense_id` INT NOT NULL,
  PRIMARY KEY (`situation_id`, `offense_id`),
  INDEX `fk_situation_has_offence_offence1_idx` (`offense_id` ASC) VISIBLE,
  INDEX `fk_situation_has_offence_situation1_idx` (`situation_id` ASC) VISIBLE,
  CONSTRAINT `fk_situation_has_offence_situation1`
    FOREIGN KEY (`situation_id`)
    REFERENCES `sentinel`.`situation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_situation_has_offence_offence1`
    FOREIGN KEY (`offense_id`)
    REFERENCES `sentinel`.`offense` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
